
version: '2'

services:
  node_todo_azure:
    image: node_todo_azure:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080